# Generated by Django 4.1.7 on 2023-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_compra_usuario_compra_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_carrito',
            name='producto_nombre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
