# Generated by Django 4.1.7 on 2023-06-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_compra_session_compra_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_carrito',
            old_name='compra',
            new_name='usuario',
        ),
    ]
