# Generated by Django 4.1.7 on 2023-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_rename_compra_detalle_carrito_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_carrito',
            old_name='usuario',
            new_name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
