# Generated by Django 4.1.7 on 2023-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_rename_usuario_detalle_carrito_compra_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalle_carrito',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detalle_carrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
