# Generated by Django 4.1.7 on 2023-06-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_alter_compra_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='estado',
            new_name='entregado',
        ),
    ]
