# Generated by Django 4.1.7 on 2023-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_rename_estado_compra_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
