# Generated by Django 4.1.7 on 2023-06-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_marca_alter_producto_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='sub_categoria',
            new_name='subcategoria',
        ),
    ]
