# Generated by Django 4.1.7 on 2023-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_sub_categoria_producto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='id',
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='subcategoría'),
        ),
    ]
