# Generated by Django 4.1.7 on 2023-06-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_subcategoria_id_alter_subcategoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
    ]
