# Generated by Django 4.1.7 on 2023-05-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
